spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/carcarehome?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Google OAuth
google.client.id=585051909821-n253vlhirijnmkol9oodtt8jsqts0jot.apps.googleusercontent.com

# Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gp406509@gmail.com
spring.mail.password=pbskignprdhjdjxy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true